#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "os"
    template = "{{.Icon}} "
    style = "plain"
    foreground = "#26C6DA"

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = "#B7BDF8"
    background = 'transparent'
    template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \uf0c7 {{ .StashCount }}{{ end }} "

    [blocks.segments.properties]
      branch_icon = ""
      commit_icon = '@'
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "#e0eee3"
    background = "transparent"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "go"
    style = "plain"
    foreground = "#7FD5EA"
    background = "transparent"
    template = " \ue627 {{ .Full }} "

  [[blocks.segments]]
    type = "battery"
    style = "plain"
    foreground = "#193549"
    background = "transparent"
    foreground_templates = [
      "{{if gt .Percentage 40}}green{{end}}",
      "{{if lt .Percentage 40}}red{{end}}",
    ]
    template = " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }} "

    [blocks.segments.properties]
      charging_icon = " "
      charged_icon = " "

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '
